# $FreeBSD$

PORTNAME=	mm16dread
PORTVERSION=	0.1
CATEGORIES=	misc
MASTER_SITES=	http://www.pozsarzs.hu/packages/software/mm16dread

MAINTAINER=	pozsarzs@gmail.com
COMMENT=	Status reader program for MM16D device

GNU_CONFIGURE=	yes

.include <bsd.port.mk>

CONFIGURE_ARGS+=stagedir=$(STAGEDIR)/$(PREFIX)

